const vocabulario = [
  { front: "ひっこし", back: "Mudanza" },
{ front: "おしゃれ", back: "Con estilo / Elegante" },
{ front: "きちんと", back: "Ordenadamente / Correctamente" },
{ front: "ずっと", back: "Todo el tiempo / Mucho más" },
{ front: "りこん", back: "Divorcio" },
{ front: "まいつき", back: "Cada mes / Mensualmente" },
  { front: "うすい", back: "Delgado" },
  { front: "ふとい", back: "Grueso" },
  { front: "こい", back: "Denso" },
  { front: "かるい", back: "Ligero" },
  { front: "せまい", back: "Estrecho" },
  { front: "ひろい", back: "Amplio" },
  { front: "あさい", back: "Superficial" },
  { front: "ふかい", back: "Profundo" },
  { front: "あつい", back: "Grueso (objeto)" },
  { front: "あたたかい", back: "Cálido" },
  { front: "あつい", back: "Caliente" },
  { front: "つめたい", back: "Frío (al tacto)" },
  { front: "すずしい", back: "Fresco (clima)" },
  { front: "あまい", back: "Dulce" },
  { front: "からい", back: "Picante" },
  { front: "にがい", back: "Amargo" },
  { front: "しおからい", back: "Salado" },
  { front: "おもい", back: "Pesado" },
  { front: "おそい", back: "Lento" },
  { front: "おおい", back: "Mucho" },
  { front: "すくない", back: "Poco" },
  { front: "ながい", back: "Largo" },
  { front: "みじかい", back: "Corto" },
  { front: "はやい", back: "Rápido" },
  { front: "たかい", back: "Alto" },
  { front: "ひくい", back: "Bajo" },
  { front: "あかるい", back: "Claro" },
  { front: "くらい", back: "Oscuro" },
  { front: "いい", back: "Bueno" },
  { front: "わるい", back: "Malo" },
  { front: "あたらしい", back: "Nuevo" },
  { front: "ふるい", back: "Viejo" },
  { front: "きれい", back: "Limpio / Hermoso" },
  { front: "きたない", back: "Sucio" },
  { front: "しんせつ", back: "Amable" },
  { front: "げんき", back: "Saludable / Animado" },
  { front: "ゆうめい", back: "Famoso" },
  { front: "にぎやか", back: "Animado (lugar)" },
  { front: "しずか", back: "Tranquilo (lugar)" },
  { front: "べんり", back: "Conveniente" },
  { front: "ふべん", back: "Inconveniente" },
  { front: "たいせつ", back: "Importante" },
  { front: "じょうぶ", back: "Fuerte / Robusto" },
  { front: "すてき", back: "Encantador / Maravilloso" },
{ front: "しく", back: "Extender / Poner (por ejemplo, un mantel o una alfombra)" },
{ front: "わかす", back: "Hervir / Calentar agua" },
{ front: "ひたす", back: "Remojar / Empapar" },
{ front: "しんじる", back: "Creer / Confiar" },
{ front: "さそう", back: "Invitar / Animar a alguien a hacer algo" },
{ front: "たずねる", back: "Visitar / Preguntar" },
  // Nuevas palabras agregadas
  { front: "うかがう", back: "Consultar / Preguntar (forma humilde)" },
  { front: "あやまる", back: "Disculparse" },
  { front: "まちがえる", back: "Equivocarse" },
  { front: "みおくる", back: "Despedirse / Acompañar al partir" },
  { front: "かける", back: "Colgar" },
  { front: "ごみ", back: "Basura" },
  { front: "じしん", back: "Terremoto" },
  { front: "たいふう", back: "Tifón / Viento fuerte" },
  { front: "たんす", back: "Mueble / Cajonera" },
  { front: "よやく", back: "Reserva / Cita" },
  { front: "そうだん", back: "Consulta / Conversación" },
  { front: "ほか", back: "Otro / Demás" },
  { front: "きっと", back: "Seguro / Sin duda / Probablemente" },
{ front: "ぺらぺら", back: "Fluido / Hablando con soltura" },
{ front: "ほとんど", back: "Casi / La mayoría" },
{ front: "やっと", back: "Por fin / Finalmente" },
{ front: "しゃべる", back: "Hablar / Charlar" },
{ front: "あまり", back: "No mucho / Poco (usado con negativo)" },
{ front: "りょうきん", back: "Tarifa / Precio / Costo" },
{ front: "たび", back: "Viaje" },
{ front: "もどる", back: "Regresar / Volver" },
{ front: "めったに", back: "Raramente / Casi nunca (usado con negativo)" },
{ front: "なくなる", back: "Desaparecer / Perderse / Morir (formal)" }
];


  const kanjisN4 = [
    {front: "料金", back: "りょうきん — Tarifa / Precio / Costo"},
  { front: "工場", back: "こうじょう — Fábrica" },
{ front: "貸す", back: "かす — Prestar / Alquilar" },
{ front: "湯", back: "ゆ — Agua caliente" },
{ front: "服", back: "ふく — Ropa" },
  { front: "明", back: "あかるい - claro, luminoso" },
  { front: "安", back: "やすい - barato, tranquilo" },
  { front: "医", back: "いしゃ - médico" },
  { front: "育", back: "そだつ／そだてる - crecer / criar" },

  { front: "使う", back: "つかう - usar" },
  { front: "作る", back: "つくる - hacer, crear" },
  { front: "泣く", back: "なく - llorar" },
  { front: "立つ", back: "たつ - ponerse de pie" },
  { front: "座る", back: "すわる - sentarse" },
  { front: "子供", back: "こども - niño, hijo" },
  { front: "心配", back: "しんぱい - preocupación" },
  { front: "店長", back: "てんちょう - gerente de tienda" },
  { front: "悪い", back: "わるい - malo" },
  { front: "言葉", back: "ことば - palabra, idioma" },

  { front: "取る", back: "とる - tomar, agarrar" },
  { front: "起きる", back: "おきる - levantarse, despertarse" },
  { front: "持つ", back: "もつ - tener, sostener" },
  { front: "待つ", back: "まつ - esperar" },
  { front: "飛ぶ", back: "とぶ - volar" },
  { front: "遊ぶ", back: "あそぶ - jugar, divertirse" },
  { front: "手伝う", back: "てつだう - ayudar" },
  { front: "習う", back: "ならう - aprender (de alguien)" },
  { front: "並ぶ", back: "ならぶ - alinearse, ponerse en fila" },

  // nuevos
  { front: "起こる", back: "おこる - ocurrir, suceder" },
  { front: "並べる", back: "ならべる - colocar en fila" },
  { front: "調べる", back: "しらべる - investigar, examinar" },
  { front: "面白い", back: "おもしろい - interesante, divertido" },
  { front: "切る", back: "きる - cortar" },
  { front: "泳ぐ", back: "およぐ - nadar" },
  { front: "寝る", back: "ねる - dormir" },
  { front: "忙しい", back: "いそがしい - ocupado" },
  { front: "家族", back: "かぞく - familia" },
  { front: "写真", back: "しゃしん - fotografía" },
  { front: "新聞", back: "しんぶん - periódico" },
  { front: "辞書", back: "じしょ - diccionario" },
  { front: "走る", back: "はしる - correr" },
  { front: "歩く", back: "あるく - caminar" },
  { front: "勉強", back: "べんきょう - estudio" },
  { front: "部屋", back: "へや - habitación" },
  { front: "運転", back: "うんてん - conducir" },
  { front: "運動", back: "うんどう - ejercicio" },
  { front: "授業", back: "じゅぎょう - clase, lección" },
  { front: "食事", back: "しょくじ - comida" },
  { front: "教室", back: "きょうしつ - aula" },
  { front: "合格", back: "ごうかく - aprobar (un examen)" },
  { front: "食堂", back: "しょくどう - comedor" },
  { front: "生活", back: "せいかつ - vida cotidiana" },
  { front: "楽しい", back: "たのしい - divertido" },
  { front: "薬", back: "くすり - medicina" },
  { front: "甘い", back: "あまい - dulce" },

  { front: "開ける", back: "あける - abrir (algo)" },
  { front: "開く", back: "あく - abrirse" },
  { front: "閉める", back: "しめる - cerrar (algo)" },
  { front: "閉まる", back: "しまる - cerrarse" },
  { front: "消す", back: "けす - apagar, borrar" },
  { front: "帰る", back: "かえる - volver, regresar" },
  { front: "倒す", back: "たおす - derribar, tumbar" },
  { front: "倒れる", back: "たおれる - caerse, colapsar" },
  { front: "割る", back: "わる - romper, partir (algo)" },
  { front: "割れる", back: "われる - romperse, partirse" },
  { front: "燃やす", back: "もやす - quemar (algo)" },
  { front: "燃える", back: "もえる - arder, quemarse" },
  { front: "伝える", back: "つたえる - transmitir, comunicar" },
  { front: "伝わる", back: "つたわる - transmitirse, llegar" },
  { front: "付ける", back: "つける - prender, adjuntar, aplicar" },
  { front: "付く", back: "つく - prenderse, adherirse" },
  { front: "止める", back: "とめる - detener (algo)" },
  { front: "止まる", back: "とまる - detenerse" },
  { front: "入れる", back: "いれる - meter, poner dentro" },
  { front: "入る", back: "はいる - entrar" },
  { front: "見つける", back: "みつける - encontrar" },
  { front: "見つかる", back: "みつかる - ser encontrado" },
  { front: "届ける", back: "とどける - entregar" },
  { front: "届く", back: "とどく - llegar (algo entregado)" },
  { front: "落とす", back: "おとす - dejar caer (algo)" },
  { front: "落ちる", back: "おちる - caerse" },
  { front: "流す", back: "ながす - dejar fluir, verter" },
  { front: "流れる", back: "ながれる - fluir" },
  { front: "減らす", back: "へらす - reducir (algo)" },
  { front: "減る", back: "へる - reducirse, disminuir" },
  { front: "助ける", back: "たすける - ayudar, rescatar" },
  { front: "助かる", back: "たすかる - ser salvado, sobrevivir" },
  { front: "隠す", back: "かくす - esconder (algo)" },
  { front: "隠れる", back: "かくれる - esconderse" },
  { front: "育てる", back: "そだてる - criar, educar" },
  { front: "育つ", back: "そだつ - crecer" },
  { front: "乗せる", back: "のせる - subir (algo/alguien) a un vehículo" },
  { front: "乗る", back: "のる - subir(se) a un vehículo" },
  { front: "地図", back: "ちず - mapa" },
  { front: "相談", back: "そうだん - consulta, hablar con alguien" },
  { front: "体重", back: "たいじゅう - peso corporal" },
  { front: "家族", back: "かぞく - familia" },
  { front: "父", back: "ちち - mi padre" },
  { front: "母", back: "はは - mi madre" },
  { front: "お父さん", back: "おとうさん - padre (de otro / forma respetuosa)" },
  { front: "お母さん", back: "おかあさん - madre (de otro / forma respetuosa)" },
  { front: "兄", back: "あに - mi hermano mayor" },
  { front: "姉", back: "あね - mi hermana mayor" },
  { front: "弟", back: "おとうと - hermano menor" },
  { front: "妹", back: "いもうと - hermana menor" },
  { front: "兄弟", back: "きょうだい - hermanos" },
  { front: "姉妹", back: "しまい - hermanas" },
  { front: "祖父", back: "そふ - mi abuelo" },
  { front: "祖母", back: "そぼ - mi abuela" },
  { front: "おじいさん", back: "abuelo (de otro / forma respetuosa)" },
  { front: "おばあさん", back: "abuela (de otro / forma respetuosa)" },
  { front: "夫", back: "おっと - mi esposo" },
  { front: "妻", back: "つま - mi esposa" },
  { front: "主人", back: "しゅじん - esposo / amo de casa" },
  { front: "家内", back: "かない - esposa (forma humilde)" },
  { front: "子供", back: "こども - hijo / niño" },
  { front: "息子", back: "むすこ - hijo (varón)" },
  { front: "娘", back: "むすめ - hija" },
  { front: "引く", back: "ひく - hacer tirón, atraer" },
  { front: "急ぐ", back: "いそぐ - apurarse / darse prisa" },
  { front: "上がる", back: "あがる - subir / elevarse / aumentar" },
  { front: "下がる", back: "さがる - bajar / descender / disminuir" },
  { front: "送る", back: "おくる - enviar / mandar / acompañar / despedir" },
    { front: "病", back: "びょう - enfermedad / estar enfermo" },
  { front: "質", back: "しつ - calidad / sustancia / carácter" },
  { front: "病気", back: "びょうき - enfermedad" },
  { front: "質問", back: "しつもん - pregunta" },
     { front: "答える", back: "こたえる - responder / contestar" },
  { front: "音", back: "おと - sonido / ruido" },
  { front: "歌", back: "うた - canción" },
  { front: "週", back: "しゅう - semana" },
  { front: "室", back: "しつ - habitación / sala / cuarto" },
  { front: "図書館", back: "としょかん - biblioteca" },
     { front: "館", back: "かん - edificio / sala / institución" },
  { front: "春", back: "はる - primavera" },
  { front: "秋", back: "あき - otoño" },
  { front: "冬", back: "ふゆ - invierno" },
  { front: "夏", back: "なつ - verano" },
  { front: "旅館", back: "りょかん - posada japonesa tradicional / hospedaje" },
  { front: "貸す", back: "かす - prestar / alquilar" },
  { front: "鳥", back: "とり - ave / pájaro" },
  { front: "魚", back: "さかな - pez / pescado" },
  { front: "馬", back: "うま - caballo" },
  { front: "虎", back: "とら - tigre" },
  { front: "飯", back: "めし - comida / arroz cocido" },
  { front: "勤める", back: "つとめる - trabajar / estar empleado en" }, 
      { front: "海", back: "うみ - mar / océano" },
  { front: "売", back: "うる - vender" },
  { front: "知", back: "しる - saber / conocimiento / sabiduría" },
  { front: "道", back: "みち - camino / calle / distrito / viaje / curso" },
  { front: "集", back: "あつめる - reunir / juntar / encontrarse" },
  { front: "別", back: "わかれる / わける - separar / divergir / ramificarse" },
  { front: "物", back: "もの - cosa / objeto / materia" },
  { front: "使", back: "つかう - usar / mandar / mensajero / embajador" },
  { front: "品", back: "しな - bienes / artículos / refinamiento / dignidad" },
  { front: "計", back: "はかる - planear / medir / esquema" },
  { front: "死", back: "しぬ - morir / muerte" },
  { front: "特", back: "とく - especial" },
  { front: "近道", back: "ちかみち - atajo" },
  { front: "選択", back: "せんたく - elección / selección" },
  { front: "遠足", back: "えんそく - excursión" },
  { front: "特別", back: "とくべつ - especial / extraordinario" },
    { front: "始", back: "はじめる - comenzar / empezar" },
  { front: "朝", back: "あさ - mañana" },
  { front: "運", back: "はこぶ - transportar / llevar / suerte / destino" },
  { front: "終", back: "おわる - terminar / finalizar" },
  { front: "台", back: "うてな - pedestal / soporte / contador para máquinas o vehículos" },
  { front: "広", back: "ひろい - amplio / espacioso" },
  { front: "住", back: "すむ - vivir / residir / habitar" },
  { front: "運転", back: "うんてん - conducir / manejo de vehículos" },
      { front: "無", back: "ない - nada / inexistente / ninguno / vacío" },
  { front: "真", back: "ま / まこと - verdadero / realidad / secta budista" },
  { front: "有", back: "ある - poseer / tener / existir / suceder" },
  { front: "口", back: "くち - boca" },
  { front: "少", back: "すくない / すこし - poco / pocos / un poco" },
  { front: "町", back: "まち - pueblo / ciudad / barrio / calle" },
  { front: "料", back: "りょう - tarifa / materiales / ingredientes" },
  { front: "工", back: "こう / く / ぐ - artesanía / construcción" },
  { front: "建", back: "たてる - construir / edificar" },
  { front: "空", back: "そら / から / あく / すく / むなしい - cielo / vacío / desocupado / hueco / vano" },
  { front: "工学", back: "こうがく - ingeniería" }
];

const numeros = [
  // 🗓️ Días del mes (difíciles e irregulares)
  { front: "一日", back: "ついたち" },
  { front: "二日", back: "ふつか" },
  { front: "三日", back: "みっか" },
  { front: "四日", back: "よっか" },
  { front: "五日", back: "いつか" },
  { front: "六日", back: "むいか" },
  { front: "七日", back: "なのか" },
  { front: "八日", back: "ようか" },
  { front: "九日", back: "ここのか" },
  { front: "十日", back: "とおか" },
  { front: "十四日", back: "じゅうよっか" },
  { front: "二十日", back: "はつか" },
  { front: "二十四日", back: "にじゅうよっか" },
  { front: "二十九日", back: "にじゅうくにち" },
  { front: "三十日", back: "さんじゅうにち" },
  { front: "三十一日", back: "さんじゅういちにち" },

  // 🌸 Meses
  { front: "一月", back: "いちがつ" },
  { front: "二月", back: "にがつ" },
  { front: "三月", back: "さんがつ" },
  { front: "四月", back: "しがつ" },
  { front: "五月", back: "ごがつ" },
  { front: "六月", back: "ろくがつ" },
  { front: "七月", back: "しちがつ" },
  { front: "八月", back: "はちがつ" },
  { front: "九月", back: "くがつ" },
  { front: "十月", back: "じゅうがつ" },
  { front: "十一月", back: "じゅういちがつ" },
  { front: "十二月", back: "じゅうにがつ" },

  // 📆 Fechas completas
  { front: "一月一日", back: "いちがつついたち" },
  { front: "三月三日", back: "さんがつみっか" },
  { front: "四月十日", back: "しがつとおか" },
  { front: "五月五日", back: "ごがついつか" },
  { front: "七月七日", back: "しちがつなのか" },
  { front: "八月十五日", back: "はちがつじゅうごにち" },
  { front: "九月九日", back: "くがつここのか" },
  { front: "十月十日", back: "じゅうがつとおか" },
  { front: "十一月二十日", back: "じゅういちがつはつか" },
  { front: "十二月三十一日", back: "じゅうにがつさんじゅういちにち" }
];

const gramatica = [
  { front: "のような", back: "Algo como otra cosa (apariencia, físico)" },
    { front: "のように", back: "Algo como otra cosa (manera, acción)" },
    { front: "～そう", back: "Parece que..." },
  { front: "～たい", back: "Querer hacer algo (forma volitiva de un verbo)" },
  { front: "～ながら", back: "mientras" },
  { front: "～ことがある", back: "Expresa que algo ha sucedido ocasionalmente" },
  { front: "～すぎる", back: "Demasiado..." },
  { front: "～でしょう", back: "Suposición, probablemente" },
  { front: "～てもいい", back: "Está bien hacer..., permiso" },
    { front: "～てある", back: "Acción realizada o completada con un efecto presente (algo hecho y dejado así)" }
,{ front: "ために", back: "Para, con el fin de..." },
  { front: "のに", back: "Aunque, a pesar de..." },
  { front: "だけ", back: "Solo, únicamente" },
  { front: "そして", back: "Y, además" },
  { front: "どうして", back: "Por qué" },
  { front: "どのような", back: "Qué tipo de..." },
  { front: "どのように", back: "De qué manera..., cómo..." },
  { front: "ないで", back: "Sin hacer algo / no hagas..." },
    { front: "ようになる", back: "Algo logrado con esfuerzo / llegar a poder hacer algo" },
  { front: "ようにする", back: "Hacer lo posible para hacer algo / procurar hacer algo" },
    { front: "Vる + ために", back: "Para..., con el fin de..., por causa de algo" },
    { front: "Vる + と", back: "Al... おすと(Al apretar)" },
{ front: "なかなか+V-ない", back: "Me cuesta mucho..." }

];
